[workspace]
resolver = "2"
members = [
    "crates/manimgx-core",
    "crates/manimgx-encode",
    "crates/manimgx-render",
    "crates/manimgx-metal",
    "crates/manimgx-py",
]
default-members = [
    "crates/manimgx-core",
    "crates/manimgx-encode",
    "crates/manimgx-render",
    "crates/manimgx-metal",
]

[workspace.dependencies]
glam = "0.29"
bytemuck = { version = "1", features = ["derive"] }
log = "0.4"
