[package]
name = "manimgx-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "manimgx"
crate-type = ["cdylib"]

[dependencies]
manimgx-core = { path = "../manimgx-core" }
manimgx-render = { path = "../manimgx-render" }
manimgx-metal = { path = "../manimgx-metal" }
pyo3 = { version = "0.28", features = ["extension-module"] }
glam = { workspace = true }
log = { workspace = true }

[features]
time_profile = ["manimgx-render/time_profile", "manimgx-metal/time_profile"]
