[package]
name = "manimgx-render"
version = "0.1.0"
edition = "2021"

[dependencies]
manimgx-core = { path = "../manimgx-core" }
manimgx-encode = { path = "../manimgx-encode" }
wgpu = "24"
bytemuck = { workspace = true }
glam = { workspace = true }
log = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"], optional = true }

[features]
time_profile = []
png_debug = ["image"]
